### ISSUE TITLE
Current pcap draft doesn't include all the link types

### ISSUE THREAD

**Issue by kayoub5** [pcapng/pcapng#102]
The current list of link types contains about 128 link types, unfortunately the list there is incomplete.
* The link on [tcpdump website](https://www.tcpdump.org/linktypes.html) defines around 113 link types
* [pcap-common.c](https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-common.c) defines around 205 link types

The additional 90 or so link types already defined in `pcap-common.c` needs to be taken into consideration to prevent conflict.

**Comment by guyharris** [comment]
> The additional 90 or so link types already defined in pcap-common.c needs to be taken into consideration to prevent conflict.

Values in the range `DLT_MATCHING_MIN` to `DLT_MATCHING_MAX`, from `pcap/dlt.h`, are not available for assignment.

We can add "reserved for" entries for the ones that don't have specifications.

**Comment by kayoub5** [comment]
Sounds good.

One small detail, `DLT_MATCHING_MAX` will soon change due to https://github.com/the-tcpdump-group/libpcap/pull/934

**Comment by guyharris** [comment]
They should be there now.  Some ranges *are* marked as "not to be used".

**Comment by mcr** [comment]
So, please don't stress about getting everything perfect.
We have to get the document adopted (or sponsored), and then have a
conversation with IANA about how to transfer this large table.
(They may prefer another format)
Not that good data isn't better than bad data, I'm just saying: let's get the
format right.
