### ISSUE TITLE
Change the type/code request point of contact?

### ISSUE THREAD

**Issue by geraldcombs** [pcapng/pcapng#104]
The current pcapng specification tells users to request new block types, block option codes, and decryption secrets types from pcap-ng-format@winpcap.org. That's the last active mailing list on a server that's otherwise inactive and doesn't get much administrative attention.

Would it make sense to change the point of contact to this repository, e.g. by telling users to create an issue or open a pull request?

**Comment by guyharris** [comment]
Yes.
