### ISSUE TITLE
IDB: Can it appear anywhere within a section?

### ISSUE THREAD

**Issue by daviessm** [pcapng/pcapng#116]
From reading the spec I can't see whether all IDBs must appear immediately after the SHB or whether they can occur anywhere within a section. Can this be made explicit?

**Comment by guyharris** [comment]
[Section 3.4 "Physical File Layout"](https://pcapng.github.io/pcapng/draft-ietf-opsawg-pcapng.html#name-physical-file-layout) in [Figure 6](https://pcapng.github.io/pcapng/draft-ietf-opsawg-pcapng.html#fssample-full) gives as an example a file with an IDB that does *not* appear immediately after the SHB.

I will add text to [section 4.2 "Interface Description Block"](https://pcapng.github.io/pcapng/draft-ietf-opsawg-pcapng.html#name-interface-description-block) text to explicitly indicate that the only restriction, within a section, on the location of IDBs is that an IDB for an interface must occur before any blocks that refer to that interface.

**Comment by guyharris** [comment]
> I will add text to [section 4.2 "Interface Description Block"](https://pcapng.github.io/pcapng/draft-ietf-opsawg-pcapng.html#name-interface-description-block) text to explicitly indicate that the only restriction, within a section, on the location of IDBs is that an IDB for an interface must occur before any blocks that refer to that interface.

Done in 96a3afd74773307ca1892e87954891bd177ecd3f.
