### ISSUE TITLE
Need to decide on the official name for this file format, and stick to it.

### ISSUE THREAD

**Issue by hadrielk** [pcapng/pcapng#15]
The document generally uses the word "pcapng" to describe the file format, but uses "pcap-ng" in the introduction.
It would be nice to stick to one name, at least within the document. I just don't know what the official name is. :smirk: 

(as an aside, some web sites use "PCAP-NG" (all caps), or "PcapNg" or other variations)

**Comment by guyharris** [comment]
I'm not sure that all members of the pcap-ng mailing list have subscribed to this repository, so at least some issues might be better sent to the list in addition to, or rather than, being filed as issues.

**Comment by hadrielk** [comment]
The term is now 'pcapng' throughout the file, so closing this issue.
