### ISSUE TITLE
Stale references to old repo location mcr/pcapng

### ISSUE THREAD

**Issue by lukem** [pcapng/pcapng#83]
There's a few stale references to https://github.com/mcr/pcapng and https://mcr.github.io/pcapng in the tree.
The former can be replaced with https://github.com/pcapng/pcapng
Not sure what to do about the latter.

**Comment by fxlb** [comment]
Partial fix with 19019ea6338099c7e75c125e789b8033dba7c62b.

**Comment by mcr** [comment]
Should be fixed now.
