### ISSUE TITLE
About PR #67 and files added

### ISSUE THREAD

**Issue by fxlb** [pcapng/pcapng#92]
The merge of PR #67 has added the files `draft-tuexen-opsawg-pcapng.txt` and `draft-tuexen-opsawg-pcapng.html`.

Expected ?

**Comment by guyharris** [comment]
> Expected ?

No - I didn't even notice that.  I'll remove them.

**Comment by guyharris** [comment]
Done in d6779400a3bbbdde77909e038c403128c5856eb7.
