### ISSUE TITLE
Current Committed Specs Links Broken

### ISSUE THREAD

**Issue by shaggygi** [pcapng/pcapng#93]
Are others seeing this?  Try link from main README...

http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?url=https://raw.githubusercontent.com/pcapng/pcapng/master/draft-tuexen-opsawg-pcapng.xml&modeAsFormat=txt/pdf&type=ascii

**Comment by guyharris** [comment]
xml2rfc.tools.ietf.org appears to be down; we'll wait to see if it comes back up again.

**Comment by shaggygi** [comment]
Okay.  Looks like they are back online.  Thx
