### ISSUE TITLE
Stale document - https://pcapng.github.io/pcapng/

### ISSUE THREAD

**Issue by bubbasnmp** [pcapng/pcapng#97]
Lazy googling "pcapng file format" returns https://pcapng.github.io/pcapng/ which is beautifully formatted and easy to read but out of date.

**Comment by guyharris** [comment]
@mcr, can we somehow arrange to have the Markdown converted either to RFC XML that we can feed to the RFC XML to xxx converters, or converted directly to HTML, so people who want to read the spec can get to a formatted document?

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > @mcr, can we somehow arrange to have the Markdown converted either to
    > RFC XML that we can feed to the RFC XML to xxx converters, or converted
    > directly to HTML, so people who want to read the spec can get to a
    > formatted document?

kramdown | xml2rfc -html
is as easy as just "xml2rfc -html", so if we are actively doing something
then, we can just actively use markdown.

If you are asking if we can regularly commit a .html file, I do not object to
that at all.  That's trivial, but people hate having "output" in .github.

There is a github webhook that can be setup to have travis/circleci update the
gh-pages branch which feeds the github.io.
I can try to set that up next time I edit.

**Comment by guyharris** [comment]
> There is a github webhook that can be setup to have travis/circleci update the
gh-pages branch

(Sigh, why did my parents give me the same initials as GitHub? :-))

> which feeds the github.io.

So does that mean that the gh-pages branch of the pcapng/pcapng repository is a ["publishing source"](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#publishing-sources-for-github-pages-sites) for pcapng.github.io?

And does that web hook mean that a CI run, done whenever something's committed to the pcapng/pcapng repository, would run kramdown | xml2rfc -html to generate HTML, and then commit that HTML to the gh-pages branch, or something such as that?

Or does it do something else?

**Comment by guyharris** [comment]
OK, so @mcr has set up the webhook, and the current version of the pcapng draft is [here](https://pcapng.github.io/pcapng/draft-tuexen-opsawg-pcapng.html).
