### ISSUE TITLE
broken links from pcapng README.md

### ISSUE THREAD

**Issue by laf0rge** [pcapng/pcapng#98]
Most of the links linking to rendered versions of the draft fail:

* "Editor's Copy" (https://mcr.github.io/pcapng/#go.draft-tuexen-opsawg-pcapng.html) is a 404
* "Current committed version as HTML" (http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?url=https://raw.githubusercontent.com/pcapng/pcapng/master/draft-tuexen-opsawg-pcapng.xml&modeAsFormat=html/ascii&type=ascii) is 404
* "Currnet committed version as PDF" and as Text equally are 404

**Comment by guyharris** [comment]
Yes, I think @mcr is working on some changes so that HTML pages (or XML pages that we can shove through xml2rfc.tools.ietf.org) can be generated from the now-in-extended-Markdown source for the draft.  I think the pages will end up on [GitHub Pages](https://pages.github.com).

**Comment by mcr** [comment]
okay, circleci magic invoked, and it should rebuild everything now.
The pcap (legacy) hasn't been reposted to the IETF datatracker yet, so the diff links won't work yet.
